services:
  app:
    build: 
      context: .
      args:
        - GIT_USERNAME=${git_username}
        - GIT_TOKEN=${git_token}
    volumes:
      - .:/app
      - /projetos/arquivos:/projetos/arquivos
      - /projetos/estudos-middle:/projetos/estudos-middle
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

