services:
  app:
    build: 
      context: .
      args:
        - GIT_USERNAME=${git_username}
        - GIT_TOKEN=${git_token}
    volumes:
      - .:/app
      - ~/projetos/arquivos:/home/projetos/arquivos
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

